### ISSUE TITLE
JSon parsen 

### ISSUE THREAD

**Issue by frankdoesburg** [frankdoesburg/WTTV2015#11]
http://stackoverflow.com/questions/9605913/how-to-parse-json-in-android
http://www.androidhive.info/2012/01/android-json-parsing-tutorial/

**Comment by frankdoesburg** [comment]
gebruik GSon library http://www.javacodegeeks.com/2011/01/android-json-parsing-gson-tutorial.html

**Comment by frankdoesburg** [comment]
http://kylewbanks.com/blog/Tutorial-Android-Parsing-JSON-with-GSON

**Comment by TomDoes** [comment]
Done
