### ISSUE TITLE
Nieuwe database inladen en bewerken

### ISSUE THREAD

**Issue by frankdoesburg** [frankdoesburg/WTTV2015#12]
Blob omzetten naar bitmap: http://androidsurya.blogspot.nl/2012/11/insert-and-retrieve-image-from-sqlite.html

**Comment by frankdoesburg** [comment]
https://www.google.nl/url?sa=t&source=web&rct=j&ei=zuCBVcecJon5ywPFubxY&url=http://stackoverflow.com/questions/7331310/how-to-store-image-as-blob-in-sqlite-how-to-retrieve-it&ved=0CB0QFjAA&usg=AFQjCNFwEn3M2PQRrwkxNvRpBlfmdQvUmA

**Comment by frankdoesburg** [comment]
Probleem bij database inladen, converteren van blob naar Bitmap geeft null terug. Kloppen de blobs in de DB op dropbox wel of zit er misschien html tussen?

**Comment by TomDoes** [comment]
Check de db die je hebt met die Explorer..  Of vraag harm even
Op 20 jun. 2015 19:38 schreef "Frank" notifications@github.com:

**Comment by frankdoesburg** [comment]
Probleem was inderdaad de byte64.
