### ISSUE TITLE
Database update code

### ISSUE THREAD

**Issue by frankdoesburg** [frankdoesburg/WTTV2015#14]
Database update werkt niet automatisch als je de oude database vervangt door een nieuwe .sqlite file. In DataBaseHelper.java in de functie checkDataBase() staan 1 regel 

 //run this line when replacing database file
  // myContext.deleteDatabase(DB_NAME);

Die kan je gebruiken om de oude database weg te gooien en dat laadt ie automatisch een nieuwe database in. Enige is dat je moet bijhouden welke DB versie we nu hebben.

**Comment by TomDoes** [comment]
Acts laden op background thread in main activity.  For speed

**Comment by TomDoes** [comment]
Werkt, moet alleen nog even netjes!!
