### ISSUE TITLE
draaiend pijltje / streepjes icoon ontbreekt linksboven

### ISSUE THREAD

**Issue by frankdoesburg** [frankdoesburg/WTTV2015#23]
Dit was er eerst nog wel. Bewuste actie Tom?

**Comment by TomDoes** [comment]
Nope,
Op 4 jul. 2015 23:25 schreef "Frank" notifications@github.com:

**Comment by frankdoesburg** [comment]
Opgelost: getActionBar().setDisplayHomeAsUpEnabled(true);
