### ISSUE TITLE
Favorieten knop werkzaam en te zien in overzicht

### ISSUE THREAD

**Issue by frankdoesburg** [frankdoesburg/WTTV2015#5]
evt. herinneringen met notificaties

**Comment by frankdoesburg** [comment]
Knop is zichtbaar, nu nog functioneel maken

**Comment by frankdoesburg** [comment]
hartjes werken inclusief opslaan in DB. 

Volgende stap is overzicht van alle favorieten in listview in favoritesActivity

**Comment by TomDoes** [comment]
Ook onderdeel hiervan is acts die al geweest zijn nog een witte overlay over het item te geven

**Comment by frankdoesburg** [comment]
witte overlay zit al in de xml (visibility = gone). Zodra ik de notificaties erin zet, komt er ook een check in die de overlay zichtbaar maakt

**Comment by TomDoes** [comment]
Overlay is onafhankelijk van notificaties toch?

2015-07-06 10:58 GMT+02:00 Frank notifications@github.com:

**Comment by frankdoesburg** [comment]
Klopt, maar ik maak het op dezelfde dag :p

**Comment by TomDoes** [comment]
Check!

Op 6 juli 2015 11:10 schreef Frank notifications@github.com:

**Comment by frankdoesburg** [comment]
gebruik http://stackoverflow.com/questions/7540724/how-to-start-notification-on-custom-datetime en vergeet niet permissions in AndroidManifest.xml te zetten http://stackoverflow.com/questions/28017943/android-how-to-set-a-notification-to-a-specific-date-in-the-future
en http://stackoverflow.com/questions/7845660/how-to-run-a-service-every-day-at-noon-and-on-every-boot/7846622#7846622

Denk er ook om dat het de alarmen bij een reboot gereset worden, zie: https://developer.android.com/training/scheduling/alarms.html

**Comment by frankdoesburg** [comment]
Notoficaties werken. Nu nog trillen en geluid toevoegen aan de notificaties in AlarmReceiver.java. http://stackoverflow.com/questions/18253482/vibrate-and-sound-defaults-on-notification, http://stackoverflow.com/questions/12006724/set-a-combination-of-vibration-lights-or-sound-for-a-notification-in-android. .setDefaults(DEFAULT_ALL) Ook kleine tekst .setContentText(getString(R.string.ping))

De minus 10 minuten moet nog worden ingesteld in ArtistDetailActivity en AlarmSetter op de starttijd (alarmen staan nu op de exacte starttijd ingesteld). 
calendar.add(Calendar.MINUTE,-10);

Daarnaast ook Toast wanneer je een favoriet instelt. 

Ook notificatie icoontje voor in android lollipop. Icoon ziet er vreemd uit door nieuwe Android guidelines.

Test ook met artiest zonder datum in DB!

**Comment by frankdoesburg** [comment]
done
